### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mischnic** [makmm/test-repo#1]
Came across this while finding the parcel error:

https://github.com/makmm/test-repo/blob/1ea45f2a264df6b5024c4e419d0221decaab99f9/js/core/router/Router.js#L96

This should be 
```js
 export default new Router() 
```
,`router` is not a defined variable.

**Comment by makmm** [comment]
Oh, thanks; i'll fix it when I get a bundler working; as the name says this is just a test repo, i'm gonna make an actual repo later. thanks x2
